### ISSUE TITLE
Converted proxies should be configurable

### ISSUE THREAD

**Issue by JorelAli** [JorelAli/CommandAPI#180]
**Please describe your suggestion**
Currently, all converted commands use a proxy. Proxies are incompatible with reflection. Have a setting to disable automatic proxying

**Please supply examples of the desired inputs and outputs**
```yml
verbose-outputs: true
create-dispatcher-json: false
plugins-to-convert: 
  - Essentials: ~
  - SkinsRestorer: ~
skip-sender-proxy:
  - SkinsRestorer
```
