### ISSUE TITLE
Command conversion for arbitrary commands

### ISSUE THREAD

**Issue by JorelAli** [JorelAli/CommandAPI#195]
**Please describe your suggestion**
Currently, the CommandAPI plugin's command converter supports converting plugin commands. This means that certain plugin-registered commands (such as those by Skript or MyCommand) cannot be executed because they are not declared by the plugin. It would be nice to have a way to register arbitrary commands with the CommandAPI

**Please supply examples of the desired inputs and outputs**
_Example:_
```yml
verbose-outputs: true
create-dispatcher-json: false
plugins-to-convert: 
  - Essentials: ~
other-commands-to-convert:
  - myothercommand
  - somethingelse
```

This could be implemented using Bukkit's `Bukkit.dispatchCommand` method.
