### ISSUE TITLE
Regression with converted commands no longer working (Possible index array out of bounds)

### ISSUE THREAD

**Issue by JorelAli** [JorelAli/CommandAPI#294]
**CommandAPI version:** 8.4.0

**Minecraft version:** 1.18.2

**What I did:**

- Add the following to the `config.yml`:
```yml
plugins-to-convert:
  - MuteManager:
    - mute <player>[api:player] (minutes|perm)
    - unmute <player>[api:player]
```
- Download the latest [MuteManager](https://dev.bukkit.org/projects/mutemanager)
- Run `/minecraft:mute @p minutes`

**Actual result:** It doesn't work. An error occurred when running the command is displayed. Hovering over it shows a potential index array out of bounds exception. No logs are produced.

**What should have happened:** The command runs as expected, as if you had run `/mute <playername> minutes`. This works perfectly in 8.2.1.
