### ISSUE TITLE
The CommandAPI needs to have much more strict configuration checking

### ISSUE THREAD

**Issue by JorelAli** [JorelAli/CommandAPI#345]
### Description

If you have the following in your `config.yml` (note the erroneous values for `other-commands-to-convert` and `skip-sender-proxy`):

```yml
# Plugins to convert (default: [])
# Controls the list of plugins to process for command conversion.
plugins-to-convert:
- LuckPerms: ~

# Other commands to convert (default: [])
# A list of other commands to convert. This should be used for commands which
# are not declared in a plugin.yml file.
other-commands-to-convert:
- LuckPerms: ~

# Skip sender proxy (default: [])
# Determines whether the proxy sender should be skipped when converting a
# command. If you are having issues with plugin command conversion, add the
# plugin to this list.
skip-sender-proxy:
- LuckPerms: ~
```

The CommandAPI exhibits strange behaviour. The CommandAPI's configuration needs to have much stricter checks to identify invalid configuration
